### PR TITLE
Change ISubscription and adding EOF messages into stream

### PR DESCRIPTION
**Pull request by AndreSteenbergen**

### CODE REVIEW

**Comment by Horusiath** [comment]
From what I've seen, there's no notion of EOF in JVM - instead they start from getting end offset at the beginning and after reaching it emitting appropriate event type. See [akka.streams.eventsourcing](https://github.com/krasserm/akka-stream-eventsourcing/blob/370c482e67280d21e2577b59291bc92df7a1f517/src/main/scala/com/github/krasserm/ases/log/KafkaEventLog.scala#L169) for more inspiration.

**Comment by AndreSteenbergen** [comment]
@Horusiath I couldn't find an endOffset in the metadata. I guess the java client is a little richer then the c# client?

**Comment by Danthar** [comment]
Anything holding this PR back ?

**Comment by AndreSteenbergen** [comment]
Actually... I have a local version using the beta 2 instead of the experimental Kafka connector. This PR would work as is, no problem.

But I can update this PR with a newer kafka client and later Akka.Net version. I think I can have a fresh PR done by tomorrow 1300 CET. That is better I guess.

**Comment by Danthar** [comment]
An update would be great. 👍 Drop a comment here once you pushed your changes, and ill take a look.

**Comment by AndreSteenbergen** [comment]
Done; I am using this code in production without issues so far. Only thing I have doubts about are the failstage parts. Kafka has a connection reaper, every 10 minutes the connection will be dropped. Raising an error, but the the producer is still able to push messages to kafka without restarting. Don't know what to do really.

**Comment by Danthar** [comment]
We fixed build issues. Needs rebase

**Comment by Danthar** [comment]
@AndreSteenbergen would you mind also updating the version prefix in the csproj  for kafka ?

**Comment by AndreSteenbergen** [comment]
will do.

**Comment by AndreSteenbergen** [comment]
I am in the process of updating all nuget packages for kafka (again) kafka 1.0.0beta3 has quite a number of differences and breaking changes. wrt beta2, 1.0.0 is supposed to be out in march. If there is a huge demand for beta3 I can make a push, but I need to alter the tests as well.

**Comment by Aaronontheweb** [comment]
@Arkatufus is this PR still necessary?

**Comment by AndreSteenbergen** [comment]
nope; there is a better nuget package already in Akka Streams

**Comment by Aaronontheweb** [comment]
Ah! I didn't realize this was for Kafka - good deal

**Pull request closed without merging**
