### PR TITLE
WIP - Added contrib project and ported Retry stage

### PR DESCRIPTION
**Pull request by marcpiechura**
This new project will contain all stages from the [jvm akka.stream.contribg project](https://github.com/akka/akka-stream-contrib). 
IMO it doesn't make much sense to create yet another repository, so those stages can life here in its own folder.

### CODE REVIEW

**Comment by Horusiath** [comment]
TBH, I've never understood the idea behind akka-streams-contrib project. If we're not sure about the API, we can mark them as experimental.

**Comment by vasily-kirichenko** [comment]
@marcpiechura https://github.com/marcpiechura/Alpakka/pull/1 please help.

**Comment by marcpiechura** [comment]
@Horusiath so you want those stages in the core repo? Would be fine for me, don’t have a strong opinion for one or the other.

**Comment by Horusiath** [comment]
I'm fine with PR to core repo (just mark it with experimental API attribute and add EXPERIMENTAL API in xmldoc).

**Comment by marcpiechura** [comment]
Alright, closing this one

**Pull request closed without merging**
