### PR TITLE
Add Azure.Messaging.EventHubs support, still need testing

### PR DESCRIPTION
**Pull request by Arkatufus**
Related to #861

### CODE REVIEW

**Comment by Arkatufus** [comment]
@wesselkranenborg @anggiputper
It would be great if you can review this PR, would love to hear some input from you.

**Comment by Arkatufus** [comment]
`Azure.Messaging.EventHubs` changes the whole public surface API, so we have to create a new NuGet package to support it, it will be released as Akka.Streams.Azure.EventHub.V5 per Microsoft naming convention.

The biggest difference in the new package is that the user is now responsible for updating checkpoints (commit in kafka), this is done by calling the `UpdateCheckpointAsync()` method inside the `ProcessContext` that is emitted for each events received.

No support for substreams, to process multiple partitions, you'd have to create multiple streams, I've made a sample in the PR that shows how to use actors to do that.

No batch processing is supported yet, we could add it in the future if there are demand for it.

**Comment by anggiputper** [comment]
This looks good, the example is also pretty easy to follow. Updating checkpoint explicitly makes sense to me too, since it is application's responsibility in the new sdk, also giving flexibility to have our own logic. But I would still request support for batch processing because our solution will need it and if it is not supported yet we might need to custom something. It would be great to have the support out of the box 👍

**Comment by anggiputper** [comment]
See that it's merged 👍  Any insight on when will the support for batch processing be available? Thanks!

**Comment by Arkatufus** [comment]
@anggiputper out of the box, `Azure.Messaging.EventHubs` only support single event processing, to support batching, we would need to derive our own client based on a base class provided in the SDK.

**Pull request merged**
