### PR TITLE
Ported `DirectoryChangesSource` file module

### PR DESCRIPTION
**Pull request by ismaelhamed**
> The `DirectoryChangesSource` will emit elements every time there is a change to a watched directory in the local filesystem, the emitted change consists of the path that was changed and an enumeration describing what kind of change it was.

This implementation is built on top the [FileSystemWatcher](https://docs.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher?view=netstandard-2.0).

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Error with your specs here:

Akka.Streams.File.Tests.DirectoryChangesSourceSpec.DirectoryChangesSource_should_emit_on_directory_changes
Expected pair3.Item1 to be Deletion, but found Modification.

**Comment by ismaelhamed** [comment]
Yep. And it always is the Linux one. I wonder if the `FileSystemWatcher` works differently in Linux.

**Comment by ismaelhamed** [comment]
Ok, so the issue is that on Linux file changes are being notified twice:

 **WINDOWS**
```
Standard Output:
[INFO][15/05/2022 09:46:08][Thread 0007][LogSource (akka://test)] Created file test1file1.sample
[INFO][15/05/2022 09:46:08][Thread 0007][LogSource (akka://test)] Changed file test1file1.sample
[INFO][15/05/2022 09:46:08][Thread 0007][LogSource (akka://test)] Deleted file test1file1.sample
```
**UBUNTU**
```
Standard Output:
[INFO][05/15/2022 09:47:27][Thread 0024][LogSource (akka://test)] Created file test1file1.sample
[INFO][05/15/2022 09:47:27][Thread 0024][LogSource (akka://test)] Changed file test1file1.sample
[INFO][05/15/2022 09:47:27][Thread 0024][LogSource (akka://test)] Changed file test1file1.sample
[INFO][05/15/2022 09:47:27][Thread 0024][LogSource (akka://test)] Deleted file test1file1.sample
```

**Comment by ismaelhamed** [comment]
Looks like people have been running into this since 2017: https://github.com/dotnet/runtime/issues/24079

**Comment by Aaronontheweb** [comment]
As long as we can design the specs to ignore that issue, I'm good with merging this in

**Comment by ismaelhamed** [comment]
Just so that I understand, exactly what'd you like to see? There's no way around this behavior, it is something that the consumer of this `Source` will have to deal with.

**Comment by Aaronontheweb** [comment]
> Just so that I understand, exactly what'd you like to see? There's no way around this behavior, it is something that the consumer of this `Source` will have to deal with.

I just want the test suite to pass - the user can deal with the quirks of the file system as there's no way around it unless there's some platform-specific setting switch we need to pass in.

**Pull request merged**
