### PR TITLE
Separate XUnit runner version from XUnit version, they are not in step

### PR DESCRIPTION
**Pull request by Arkatufus**

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Why is this necessary?

**Comment by Arkatufus** [comment]
I just wanted to have everything on the latest version, just in case it affects local testing.

**Review by Aaronontheweb — APPROVED** [review]

**Comment by Aaronontheweb** [comment]
@Arkatufus looks like we have some merge conflicts that need to be updated here

**Comment by Arkatufus** [comment]
Done.

**Pull request merged**
