### PR TITLE
SignalR AspNetCore initial implementation

### PR DESCRIPTION
**Pull request by ptjhuang**
#52

### CODE REVIEW

**Comment by ptjhuang** [comment]
Tests are not running because SignalR ASPNetCore is only available from netcoreapp2.1 onwards. But thought I better check before I put my paws on build.ps1

**Comment by Horusiath** [comment]
IMHO it's better idea skip to .NET Core 2.2 and integrate indirectly with `ChannelReader<T>`/`ChannelWriter<T>` from System.Threading.Tasks.Channels (and in .NET Core 3.0 with IAsyncEnumerables), which SignalR will use to handle streams of data. We shouldn't release something that will be obsolete or legacy in the next few weeks.

More info [here](https://docs.microsoft.com/en-us/aspnet/core/signalr/streaming?view=aspnetcore-2.2).

**Comment by ptjhuang** [comment]
Happy to change it to ChannelReader<T>/ChannelWriter<T>. I'll update the pull request over the next week or so

**Comment by ptjhuang** [comment]
@horusiath #55 nice generalised approach, thanks. 
I can rebase off that pull request. 

Had a brief look at the signalR streaming API again. Can't seem to find streaming API for client to server. Did I miss something?

If that's the case IMO it still makes sense to have a single stream instance per hub, rather than one per connection as per previous version of this plugin.

Feedback?

**Comment by ptjhuang** [comment]
@Horusiath I've given this more thought, I'm not so sure about the ChannelReader/ChannelWriter any more.

Channels are great for request-response point-to-point communication.  SignalR hubs have broadcast/group capabilities that makes it nice to use.  I would think some users might still like them without having to write their own in Akka.  For example to do a "chatroom" app quickly where one client can `Send("hello")` and the server hub simply `Clients.All.Send("hello")` to every single connected client. Also others convenience methods like `Clients.Others.Send("hello")`, or `Clients.Group("chatroom1").Send("hello")`.  All of that is scaled out with by backplanes.

I note you said earlier that API is going obsolete?  It seems to me hub methods are the main way users use SignalR - do you have something I can read that suggests it'll be changed to channels?  By using ChannelReader/ChannelWriter, users of this stream adapter will probably have to write their own code to replicate SignalR's functionality.  Granted Akka makes that fun to do, e.g. `ctx.ActorSelection("chatroom1/*").Tell("hello")`.  

It seems to me the intent of the SignalR streaming APIs are for transferring large messages in chunks, like say sending a big file over to the client.

Using ChannelReader/Writer also means this adapter needs to keep track of a channel for every connection, have a mapping between UserId and connection.  Not saying we can't do it, but seems like that's what SignalR does already.

Maybe you've got something else in mind on how this adapter works, in which case could you please elaborate.

**Comment by ptjhuang** [comment]
@Horusiath just circling back to this one, I think the channel API you've put together is a better match for direct web sockets rather than SignalR.  It's got a clear and simple send and receive port that plug well into channels.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-2.2

**Comment by Danthar** [comment]
So where does that leave this PR ?

**Comment by ptjhuang** [comment]
Accept it please? :) We're going to put it into production in any case.

Then consider starting another Alpakka: Akka.Streams.WebSockets

Taking a quote from the above article: 

> ASP.NET Core SignalR is a library that simplifies adding real-time web functionality to apps. It uses WebSockets whenever possible.

> For most applications, we recommend SignalR over raw WebSockets. SignalR provides transport fallback for environments where WebSockets is not available. It also provides a simple remote procedure call app model. And in most scenarios, SignalR has no significant performance disadvantage compared to using raw WebSockets.

**Pull request merged**
